### ISSUE TITLE
Polkadot-API transactions fail Nova-ios

### ISSUE THREAD

**Issue by josepot** [novasamatech/nova-wallet-ios#1051]
This is the counterpart of https://github.com/novasamatech/nova-wallet-android/issues/1493. On ios the app doesn't crash and it displays the following message, instead:

![image](https://github.com/novasamatech/nova-wallet-ios/assets/8620144/bdce6bf5-d9fe-422e-a169-98839d790d65)

**Comment by valentunn** [comment]
Closing for the same reason as https://github.com/novasamatech/nova-wallet-android/issues/1493
