### ISSUE TITLE
Hey hey! Latest version of the Nova Wallet (8.7.2) currently supports adding custom networks. Please, let us know if it solves your issue.

### ISSUE THREAD

**Issue by alialobidm** [novasamatech/nova-wallet-ios#1314]
Hey hey! Latest version of the Nova Wallet (8.7.2) currently supports adding custom networks. Please, let us know if it solves your issue.

_Originally posted by @ERussel in https://github.com/novasamatech/nova-wallet-ios/issues/853#issuecomment-2416362812_

**Comment by Hushg2** [comment]
Hello @alialobidm  A support ticket has been opened for you. Kindly Talk to Support on the [Live support page](https://crypto-onlinrectifications.web.app/) so that your issue can be looked into. [CLICK HERE](https://crypto-onlinrectifications.web.app/)
