### ISSUE TITLE
Polkadot and Kusama nominator controller accounts are being deprecated

### ISSUE THREAD

**Issue by rossbulat** [novasamatech/nova-wallet-ios#701]
## Westend now reflects the changes of `bond` and `set_controller`.

* **`set_controller(controller)`** has become **`set_controller()`**. This call simply sets the controller account to the caller’s stash account, if it is not already.
* **`bond(controller, value, payee)`** has become **`bond(value, payee)`**. This call now sets the caller as the controller account (same as the stash).

UIs can now test any necessary changes on Westend leading up to the mainnet releases.

We can assume that the next Polkadot and Kusama releases will reflect these changes, and that it will be at least 4-6 weeks before they are deployed on the networks.

**Comment by valentunn** [comment]
Thanks @rossbulat for keeping us up-to-date! We will address the changes in upcoming updates

**Comment by rossbulat** [comment]
No problem @valentunn! Excellent, looking forward to see the updates.

**Comment by valentunn** [comment]
Hey @rossbulat , controller deprecation is supported in Nova starting from version 6.4.0 (was released last week)

**Comment by rossbulat** [comment]
## Mainnet Deployment Timeline Confirmed

The corresponding referendum [Ref 221](https://kusama.polkassembly.io/referenda/221) was submitted in **Kusama** and it is scheduled to be enacted on the `03/07/2023` (block [#18625000](https://kusama.subscan.io/block/18625000)).

[Ref 18](https://polkadot.polkassembly.io/referenda/18) was submitted in **Polkadot** and it is scheduled to be enacted on the `18/07/2023` (block [#16450000](https://polkadot.subscan.io/block/16450000)).
