### ISSUE TITLE
Support for nomination pools 

### ISSUE THREAD

**Issue by kianenigma** [novasamatech/nova-wallet-ios#755]
I am opening this to bring up the topic of nomination pools integration in all Nova-based apps, not just IOS. 

While the feature is evolving, and the way that it will store locked funds will also evolve, I speculate that pools are here to stay, and they are the future of Polkadot native staking. 

That being said, none of the nova-based wallets yet support pools. Write operations can come next, but the fact that your funds in pools are not even shown in your wallet anymore is something that I can encourage you to fix.

A similar issue was made for subscan about "pool funds being missing". I think this is a low hanging fruit and fixing it can reduce confusion for tens of thousands of pool members, which is growing rapidly: https://github.com/subscan-explorer/subscan-issue-tracker/issues/45

Lastly, see here for a guide about how to integrate pools: https://forum.polkadot.network/t/nomination-pools-integration/361

If need be, feel free to reach out to the core staking developers community here: https://matrix.to/#/#nompools-support:matrix.parity.io

**Comment by ERussel** [comment]
Hey hey! Thank you for raising the issue. We are already working on the native integration of the nomination pools into the Nova Wallet.

**Comment by kianenigma** [comment]
Thanks for your ack. Feel free to close this then when you prefer.
