### ISSUE TITLE
staking support for Pendulum Network

### ISSUE THREAD

**Issue by yumingchangsabodota** [novasamatech/nova-wallet-ios#759]
Hi I would like to make a feature request on using nova to make staking on Pendulum Network. Thank you.

**Comment by ERussel** [comment]
Hey hey! Thank you for your request. Pendulum Network is currently using Staking Pallet based on Kilt's network implementation. We will consider adding it as we now planing to expand our staking features.

**Comment by ERussel** [comment]
Please, use https://novawallet.canny.io/feature-exploration to suggest new features in the app
