### ISSUE TITLE
New update for ERC-20 not displaying correctly

### ISSUE THREAD

**Issue by trend-ziv-y-chang** [novasamatech/nova-wallet-ios#793]
![image](https://github.com/novasamatech/nova-wallet-ios/assets/131953104/7d448e25-05de-433a-a17e-84f461cfd6d8)

As the image shows, it is not displaying the amount for ERC-20 tokens.

**Comment by ERussel** [comment]
Hey hey! It might be due to connectivity issues. Please, contact support@novawallet.io.
