### ISSUE TITLE
Referenda details show raw HTML

### ISSUE THREAD

**Issue by clund** [novasamatech/nova-wallet-ios#834]
Under governance (voting) the referenda details show up as raw html.
![IMG_118C260CC653-1](https://github.com/novasamatech/nova-wallet-ios/assets/1596463/cdc7846c-0002-4316-8695-50efb8da2910)

**Comment by ERussel** [comment]
Hey hey! Thank you for reporting. We have added base implementation for html support and it should be available in the 7.1.0 release.
